/**
 * licensed to the apache software foundation (asf) under one
 * or more contributor license agreements.  see the notice file
 * distributed with this work for additional information
 * regarding copyright ownership.  the asf licenses this file
 * to you under the apache license, version 2.0 (the
 * "license"); you may not use this file except in compliance
 * with the license.  you may obtain a copy of the license at
 *
 * http://www.apache.org/licenses/license-2.0
 *
 * unless required by applicable law or agreed to in writing, software
 * distributed under the license is distributed on an "as is" basis,
 * without warranties or conditions of any kind, either express or implied.
 * see the license for the specific language governing permissions and
 * limitations under the license.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hurricane_hurricane_Topology */

#ifndef _Included_org_hurricane_hurricane_Topology
#define _Included_org_hurricane_hurricane_Topology
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hurricane_hurricane_Topology
 * Method:    Start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_hurricane_hurricane_Topology_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
