/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hurricane_jni_OutputCollector */

#ifndef _Included_hurricane_jni_OutputCollector
#define _Included_hurricane_jni_OutputCollector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hurricane_jni_OutputCollector
 * Method:    emit
 * Signature: ([Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_hurricane_jni_OutputCollector_emit
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
