all:
	cd deps/logging/target/linux/x64/Release/build;make
	cd deps/meshy/target/linux/x64/Release/build;make
	cd target/linux/x64/Release/build;make

clean:
	cd target/linux/x64/Release/build;make clean
	cd deps/meshy/target/linux/x64/Release/build;make clean
	cd deps/logging/target/linux/x64/Release/build;make clean

install:
	cd deps/logging/target/linux/x64/Release/build;make install
	cd deps/meshy/target/linux/x64/Release/build;make install
	cd target/linux/x64/Release/build;make install
